language: python
notifications:
  email: false
python:
- '2.7'
- '3.4'
- '3.5'

before_install:
- which python
- python --version

install:
- pip install pytest
- pip freeze
script:
- py.test -v tests/
after_success:
- bash <(curl -s https://codecov.io/bash)
