language: python

notifications:
  email: false

python:
- '3.4'
- '3.5'

before_install:
- which python
- python --version

install:
- pip install psutil
- pip install pytest pytest-cov
- pip install python-coveralls
- pip freeze

script:
- py.test tests/ -v --cov=progress --cov-report term-missing

after_success:
- coveralls
