language: python

notifications:
  email: false

branches:
  only:
  - master
  - dev

python:
- '2.7'
- '3.4'
- '3.5'

before_install:
- which python
- python --version

install:
- pip install psutil
- pip install pytest pytest-cov
- pip freeze

script:
- python tests/test_progress.py
- py.test tests/ -v --cov=progression --cov-report term-missing

after_success:
- bash <(curl -s https://codecov.io/bash)
